server:
  port: 8088

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      timeout: 5s
      connect-timeout: 5s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

# Swagger 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.test.redis.redis.controller
