server:
  port: 8088

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 5s
      connect-timeout: 5s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

# Knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  production: false
  basic:
    enable: false
